1. Array Creatin Functin

In [15]:
import numpy as np

In [16]:
# Creat a array frm a list 
a = np.array([1,2,3])
print('Array a : ', a)

Array a :  [1 2 3]


In [17]:
#Creat aaaray with evenly spaced valus
b = np.arange(0,20,2) # val from  0 to 20 with step 2
print(" Array b : ", b)

 Array b :  [ 0  2  4  6  8 10 12 14 16 18]


In [18]:
#Creat aaaray with linarly spaced valus

c = np.linspace(0,1,5) #  5 val from  0 to 1 with  evenly space valuse
print(" Array c : ", c)


 Array c :  [0.   0.25 0.5  0.75 1.  ]


In [19]:
# creat an array filed with zeros
d = np.zeros((3,4), dtype=int) 
print('Array d :\n',d)

Array d :
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [20]:
# creat an array filed with ones
e = np.ones((3,4), dtype=int) 
print('Array e :\n',e)

Array e :
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [21]:
# creat an identity matrix
f = np.eye(4) 
print('Identity matrix :\n',f)

Identity matrix :
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


2 . Array Manipution functions

In [22]:
#Reshape f array
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(1,3)) #reshape to 1X3
print(" Reshaped array :\n", reshaped)

 Reshaped array :
 [[1 2 3]]


In [23]:
#flattan array  both matrix mix in one matrix is called flattened array
f1 = np.array([[1,2], [3,4]])
flattened = np.ravel(f1)  #flattan to 1D array
print('Flattened array :\n' ,flattened)

Flattened array :
 [1 2 3 4]


In [24]:
#Transpose an array
e1 = np.array([[1,2], [3,4]])
transpsed = np.transpose(e1)  #transpose array
print("Tramspsed array :\n", transpsed)




Tramspsed array :
 [[1 3]
 [2 4]]


In [25]:
#Stack array vartically
a2 = np.array([1,2])
b2 = np.array([3,4])

stacked = np.vstack([a2,b2]) #stack a and b verticaly
print("Stacked arrays:\n", stacked)

Stacked arrays:
 [[1 2]
 [3 4]]


3. Mathematical functions

In [26]:
#add two array
g = np.array([1,2,3,4,5,6,7,8,9])
added = np.add(g,2)
print("Added 2 to g:\n", added)

Added 2 to g:
 [ 3  4  5  6  7  8  9 10 11]


In [27]:
#square of each element
squared = np.power(g,2)  #square each ele
print("Squared g :\n", squared)



Squared g :
 [ 1  4  9 16 25 36 49 64 81]


In [28]:
#square  root of  each element
sqrt_val = np.sqrt(g)  #square  root of each ele
print("Squared root of g :\n", sqrt_val)



Squared root of g :
 [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]


In [29]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4 5 6 7 8 9]


In [30]:
#dot product of two arrrays

a2 = np.array([1,2,3]) 
dot_product = np.dot(a,g)
print("dot product of a and g :\n", dot_product)

ValueError: shapes (3,) and (9,) not aligned: 3 (dim 0) != 9 (dim 0)

In [ ]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [ ]:
#dot product of two arrrays

a3 = np.array([1,2,3]) 
dot_product = np.dot(a1,a)
print("dot product of a and a1 :\n", dot_product)

dot product of a and a1 :
 14


4. Statistical function

In [ ]:
 s = np.array([5,6,7,8,9,10])
 mean = np.mean(s)
 print("Mean of s:", mean)
# Standard deviation of an array


Mean of s: 7.5


In [ ]:
 # Standard deviation of an array
 std_dev = np.std(s)
 print("Standard deviation of s:", std_dev)


Standard deviation of s: 1.707825127659933


In [ ]:
 # Minimum element of an array
 minimum = np.min(s)
 print("Minimum element of s:", minimum)


Minimum element of s: 5


In [ ]:
 # Maximum element of an array
 maximum = np.max(s)
 print("Maximum element of s:", maximum)


Maximum element of s: 10


 5. Linear Algebra Functions


In [ ]:
# Create a matrix
matrix = np.array([[9, 10], [3, 4]])



In [ ]:
 # Determinant of a matrix
 determinant = np.linalg.det(matrix)
 print("Determinant of matrix:", determinant)


Determinant of matrix: 6.0000000000000036


In [ ]:
 # Inverse of a matrix

inverse = np.linalg.inv(matrix)
print("Inverse of matrix:\n", inverse)

Inverse of matrix:
 [[ 0.66666667 -1.66666667]
 [-0.5         1.5       ]]


 6. Random Sampling Functions


In [ ]:
 # Generate random values between 0 and 1
 random_vals = np.random.rand(5)  # Array of 3 random values between 0 and 1
 print("Random values:", random_vals)

Random values: [0.80979683 0.70393306 0.82473484 0.26993691 0.19836636]


In [33]:
import numpy as np

# Set seed for reproducibility
np.random.seed(0)

# Generate random values between 0 and 1
random_vals = np.random.rand(5)  
print("Random values:", random_vals)

# Generate random integers between 0 and 10
rand_ints = np.random.randint(0, 10, size=5)
print("Random integers:", rand_ints)

Random values: [0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
Random integers: [5 2 4 7 6]


7. Boolean & Logical Functions

In [52]:
# Check if all elements are True
 # all
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [51]:
# Check if all elements are True
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [50]:
# Check if all elements are True
logical_test = np.array([False, False, False])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [53]:
# Check if any elements are True
 # any

any_true = np.any(logical_test)  # Check if any are True
print("Any elements True:", any_true)

Any elements True: True


 8. Set Operations

In [55]:
# Intersection of two arrays
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)

Intersection of a and b: [3 4]


In [56]:
# Union of two arrays
union = np.union1d(set_a, set_b)
print("Union of a and b:", union)

Union of a and b: [1 2 3 4 5 6]


 9. Array Attribute Functions

In [58]:
# Array attributes
a = np.array([1, 2, 3])
shape = a.shape  # Shape of the array
size = a.size    
# Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype  # Data type of the array
print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)

Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int64


 10. Other Functions


In [59]:
 #Create a copy of an array
a = np.array([1, 2, 3])
copied_array = np.copy(a)  # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [60]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes  # Size in bytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 24


In [61]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array)  # Check if arrays share memory
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
